# This file configures bitbucket pipelines that are run whenever a change is
# made to this repository.
# 
# The default pipeline builds an executable IGB jar file and copies it to your Downloads
# folder.
# 
# To use the default pipeline to automatically build IGB and copy the IGB jar file to your
# downloads section, you need to do two things:
# 
# 1) Enable bitbucket pipelines on your repository
# 2) Define a repository variable BB_AUTH_STRING
# 
# The BB_AUTH_STRING variable should look like <username>:<app password> where "username"
# is your bitbucket user name and "app password" is an "app password" with "write" permissions
# created under your bitbucket user account settings.
# 
# Your bitbucket user account is the same as what you see in the URL to your 
# repositories in bitbucket. Don't share your app password with anyone. Note that the 
# bitbucket UI lets you delete app passwords and monitor their usage. 
# 
# Branch pipelines run when you push to a branch with a name matching release-* or
# IGBF-*. These pipelines build IGB intallers using some private assets we are not
# allowed to distribute publicly. If you would like to build IGB installers using
# these pipelines, please get in touch with Dr. Ann Loraine at 
# UNC Charlotte for assistance. 
#
# Useful links:
#
# Docker image: https://hub.docker.com/r/lorainelab/igb-maven-install4j
# Dockerfile: https://bitbucket.org/lorainelab/integrated-genome-browser-docker
#

image:
  name: hillrunner2008/igb-maven-install4j:I4J10-jre-21.0.1

definitions:
  steps:
     - step: &build-installers-for-dev
         name: Build installers and executable jar. Used by IGB core developers for testing topic branches.
         caches:
           - maven
         script:
            - curl -s -S -L -O https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/lorainelab/iipc/src/master/env.sh
            - source env.sh
            - version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            - mvn install -P release-bitbucket-pipelines
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar; filename=$BITBUCKET_BRANCH.jar"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-linux-amd64-$version.sh; filename=IGB-linux-${BITBUCKET_BRANCH}_amd64.sh"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-windows-amd64-$version.exe; filename=IGB-windows-${BITBUCKET_BRANCH}_amd64.exe"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-macos-aarch64-$version.dmg; filename=IGB-macos-${BITBUCKET_BRANCH}_aarch64.dmg"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-macos-amd64-$version.dmg; filename=IGB-macos-${BITBUCKET_BRANCH}_amd64.dmg"
     - step: &build-installers-and-artifacts-for-release
         name: Build and copy Windows, MacOS, and Linux installers, executable jar file, updates.xml, and md5sums file for release to user community.
         caches:
           - maven
         script:
            - curl -s -S -L -O https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/lorainelab/iipc/src/master/env.sh
            - source env.sh
            - version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            - mvn -B install -P release-bitbucket-pipelines
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar; filename=igb_exe-$version.jar"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-linux-amd64-$version.sh"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-windows-amd64-$version.exe"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-macos-aarch64-$version.dmg;"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/IGB-macos-amd64-$version.dmg;"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/md5sums; filename=md5sums-$version"
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"main/target/media/updates.xml; filename=updates-$version.xml"
pipelines:
  default:
    - step:
        name: Build and copy jar file with IGB code and required libraries.
        caches:
          - maven
        script:
          - mvn -B install
          - version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar; filename=IGB-$version-${BITBUCKET_REPO_OWNER}.jar"
  branches:
    main-JDK21: 
      - step: *build-installers-for-dev
    release-*:
      - step: *build-installers-and-artifacts-for-release
  custom:
    release-dev-snapshots-to-nexus:
      - step:
        caches:
          - maven
        script:
          - mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-SNAPSHOT -DgenerateBackupPoms=false
          - mvn deploy -P release-snapshots -s /root/.m2/settings.xml -Drepo.username=${DEV_NEXUS_USER} -Drepo.password=${DEV_NEXUS_PASSWORD} -Drepo.id=${DEV_NEXUS_REPOSITORY_ID}
    build-master-branch-installers:
      - step: *build-installers-for-dev
    release-to-nexus.bioviz.org:
        - step:
           caches:
               - maven
           script:
               - mvn deploy -P release-to-nexus.bioviz.org -s /root/.m2/settings.xml -Drepo.username=${NEXUS_USER} -Drepo.password=${NEXUS_PASSWORD} -Drepo.id=${NEXUS_REPOSITORY_ID}

            




