# Integrated Genome Browser bitbucket-pipelines.yml file
# Author: Sanket Patil (spatil26@uncc.edu)
# Team: IGB (http://bioviz.org)
# Only use spaces to indent your .yml configuration.
# -----
#  Image refers to the docker image hosted at docker hub.
image: 
  name: lorainelab/igb-maven-install4j:jre-1.8.0_152

# There are two configurations available - default and branches. Branches configuration has 3 sub configurations. 
# 1. IGBF-*: Any topic branch with name starting IGBF-
# 2. master
# 3. release-*
# On each commit to a branch specified in branches, Pipelines executes the scripts assigned to the branch
# Default will get triggered whenever there is a commit in a branch which is not mentioned under branches configuration.
# To run pipelines manually go to branches -> hover on the brach on which you want to execute piplines-> click on ... -> select run pipeline for the branch-> select configuration
pipelines:
  default:
    - step:
        caches:
          - maven
        script: 
          - echo "This script runs on a commit/change to the branches which are not mentioned in branch workflow.
          # Executes maven command on the IGB project
          - mvn clean install -D skipTests=false
          # Posts igb_exe.jar file under Download section of repository
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar; filename=IGB-$BITBUCKET_BRANCH.jar"
  
  branches:
    IGBF-*:
      - step:
          caches:
            - maven
          script:
            - echo "This script runs on a commit/change to the topic branch having name starting with IGBF"
            # Getting Windows and Mac Keystore for signing Windows installer. Bitbucket pipeline environment variables used here for security purpose
            - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $WINDOWS_KEYSTORE_LINK -P /opt/igb
            - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $MAC_KEYSTORE_LINK -P /opt/igb
            # Replacing Keywords with actual passwords using bitbucket pipeline environment variables
            - sed -i "s/_INSTALL4jLICENSE_/${INSTALL4J_LICENSE}/" /opt/atlassian/pipelines/agent/build/pom.xml
            - sed -i "s/_WINKEYSTOREPASSWORD_/${WIN_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
            - sed -i "s/_MACKEYSTOREPASSWORD_/${MAC_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
            # Performing maven clean install goal. Note that we are using here Profile 'release' which generates installers and additional plugins
            - mvn clean install -P release-bitbucket-pipelines
            # Creating a .zip file containing igb_exe.jar and other reference materials releted to IGB project
            - zip -r -j igb /opt/atlassian/pipelines/agent/build/igb_exe.jar /opt/atlassian/pipelines/agent/build/LICENSE.html /opt/atlassian/pipelines/agent/build/NOTICES.txt /opt/atlassian/pipelines/agent/build/README.md /opt/atlassian/pipelines/agent/build/run_igb.bat /opt/atlassian/pipelines/agent/build/run_igb.command /opt/atlassian/pipelines/agent/build/run_igb.sh 
            # Posting all required files under download section of the repository
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar; filename=IGB-$BITBUCKET_BRANCH.jar" --form files=@"main/target/media/IGB_windows-x64_9_0_1.exe; filename=IGB-$BITBUCKET_BRANCH-x64.exe" --form files=@"main/target/media/IGB_macos_9_0_1.dmg; filename=IGB-$BITBUCKET_BRANCH.dmg"

    master:
    - step:
        caches:
          - maven
        script: 
          - echo "This script runs on a commit/change to master branch."
          # Getting Windows and Mac Keystore for signing Windows installer. Bitbucket pipeline environment variables used here for security purpose
          - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $WINDOWS_KEYSTORE_LINK -P /opt/igb
          - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $MAC_KEYSTORE_LINK -P /opt/igb
          # Replacing Keywords with actual passwords using bitbucket pipeline environment variables
          - sed -i "s/_INSTALL4jLICENSE_/${INSTALL4J_LICENSE}/" /opt/atlassian/pipelines/agent/build/pom.xml
          - sed -i "s/_WINKEYSTOREPASSWORD_/${WIN_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
          - sed -i "s/_MACKEYSTOREPASSWORD_/${MAC_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
          # Performing maven clean install goal. Note that we are using here Profile 'release' which generates installers and additional plugins
          - mvn clean install -P release-bitbucket-pipelines
          # Creating a .zip file containing igb_exe.jar and other reference materials releted to IGB project
          - zip -r -j igb /opt/atlassian/pipelines/agent/build/igb_exe.jar /opt/atlassian/pipelines/agent/build/LICENSE.html /opt/atlassian/pipelines/agent/build/NOTICES.txt /opt/atlassian/pipelines/agent/build/README.md /opt/atlassian/pipelines/agent/build/run_igb.bat /opt/atlassian/pipelines/agent/build/run_igb.command /opt/atlassian/pipelines/agent/build/run_igb.sh 
           # Posting all required files under download section of the repository
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar; filename=IGB-$BITBUCKET_BRANCH.jar" --form files=@"main/target/media/IGB_windows-x64_9_0_1.exe; filename=IGB-$BITBUCKET_BRANCH-x64.exe" --form files=@"main/target/media/IGB_macos_9_0_1.dmg; filename=IGB-$BITBUCKET_BRANCH.dmg"
 
    release-*:
    - step:
        caches:
          - maven
        script: 
          - echo "This script runs on a commit/change to release branch."
          # Getting Windows and Mac Keystore for signing Windows installer. Bitbucket pipeline environment variables used here for security purpose
          - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $WINDOWS_KEYSTORE_LINK -P /opt/igb
          - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $MAC_KEYSTORE_LINK -P /opt/igb
          # Replacing Keywords with actual passwords using bitbucket pipeline environment variables
          - sed -i "s/_INSTALL4jLICENSE_/${INSTALL4J_LICENSE}/" /opt/atlassian/pipelines/agent/build/pom.xml
          - sed -i "s/_WINKEYSTOREPASSWORD_/${WIN_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
          - sed -i "s/_MACKEYSTOREPASSWORD_/${MAC_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
          # Performing maven clean install goal. Note that we are using here Profile 'release' which generates installers and additional plugins
          - mvn clean install -P release-bitbucket-pipelines
          # Creating a .zip file containing igb_exe.jar and other reference materials releted to IGB project
          - zip -r -j igb /opt/atlassian/pipelines/agent/build/igb_exe.jar /opt/atlassian/pipelines/agent/build/LICENSE.html /opt/atlassian/pipelines/agent/build/NOTICES.txt /opt/atlassian/pipelines/agent/build/README.md /opt/atlassian/pipelines/agent/build/run_igb.bat /opt/atlassian/pipelines/agent/build/run_igb.command /opt/atlassian/pipelines/agent/build/run_igb.sh 
          # Posting all required files under download section of the repository
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar" --form files=@"igb.zip" --form files=@"main/target/media/IGB_unix_9_0_1.sh" --form files=@"main/target/media/IGB_windows_9_0_1.exe" --form files=@"main/target/media/IGB_windows-x64_9_0_1.exe" --form files=@"main/target/media/IGB_macos_9_0_1.dmg" --form files=@"main/target/media/md5sums" --form files=@"main/target/media/updates.xml" --form files=@"extbundles/repository.xml" --form files=@"extbundles/optional/23andMe-snp-converter-9.0.1.jar" --form files=@"extbundles/optional/geometric-mean-9.0.1.jar" --form files=@"extbundles/optional/merge-annotation-operator-9.0.1.jar" --form files=@"extbundles/optional/igb-command-socket-9.0.1.jar" --form files=@"extbundles/optional/protannot-9.0.1.jar"