# Integrated Genome Browser bitbucket-pipelines.yml file
# Author: Sanket Patil (spatil26@uncc.edu)
# Team: IGB (http://www.bioviz.org/igb)
# Only use spaces to indent your .yml configuration.
# -----
image: 
  name: lorainelab/igb-maven-install4j:jre-1.8.0_152
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD

# There are two configurations available one is default and other one custom called 'release'
# Default will get triggered whenever there is a change in the IGB repository
# Custom configuration 'release' is for manual execution of bitbucket pipelines
# To run pipelines manually go to branches -> click on ... -> select run pipeline for the branch-> select custom configration
pipelines:
  default:
    - step:
        caches:
          - maven
        script: 
          - mvn clean install -D skipTests=false
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar"
  custom:
   release:
    - step:
        caches:
          - maven
        script: 
          - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $WINDOWS_KEYSTORE_LINK -P /opt/igb
          - wget --user $BITBUCKET_USERNAME --password $BITBUCKET_PASSWORD $MAC_KEYSTORE_LINK -P /opt/igb
          - sed -i "s/_INSTALL4jLICENSE_/${INSTALL4J_LICENSE}/" /opt/atlassian/pipelines/agent/build/pom.xml
          - sed -i "s/_WINKEYSTOREPASSWORD_/${WIN_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
          - sed -i "s/_MACKEYSTOREPASSWORD_/${MAC_KEYSTORE_PASSWORD}/" /opt/atlassian/pipelines/agent/build/pom.xml
          - mvn clean install -P release-bitbucket-pipelines
          - zip -r igb /opt/atlassian/pipelines/agent/build/igb_exe.jar /opt/atlassian/pipelines/agent/build/LICENSE.html /opt/atlassian/pipelines/agent/build/NOTICES.txt /opt/atlassian/pipelines/agent/build/README.md /opt/atlassian/pipelines/agent/build/run_igb.bat /opt/atlassian/pipelines/agent/build/run_igb.command /opt/atlassian/pipelines/agent/build/run_igb.sh 
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"igb_exe.jar" --form files=@"igb.zip" --form files=@"main/target/media/IGB_unix_9_0_1.sh" --form files=@"main/target/media/IGB_windows_9_0_1.exe" --form files=@"main/target/media/IGB_windows-x64_9_0_1.exe" --form files=@"main/target/media/IGB_macos_9_0_1.dmg" --form files=@"main/target/media/md5sums" --form files=@"main/target/media/updates.xml" --form files=@"extbundles/repository.xml" --form files=@"extbundles/optional/23andMe-snp-converter-9.0.1.jar" --form files=@"extbundles/optional/geometric-mean-9.0.1.jar" --form files=@"extbundles/optional/merge-annotation-operator-9.0.1.jar" --form files=@"extbundles/optional/igb-command-socket-9.0.1.jar" --form files=@"extbundles/optional/protannot-9.0.1.jar"
          